config_version: 1

combat:
  tagSeconds: 45
  reTagOnPearl: true
  damageMultiplier: 1.0
  banDebuffs: true
  banPotions: false

storage:
  preventChests: false
  preventEnderChests: false
  preventBarrels: false
  preventShulkerBoxes: true

transport:
  banElytra: true
  banTridents: true
  banPearls: false
  banChorus: false
  banHorses: false
  banBoats: false
  banMinecarts: false

commands:
  whitelist:
    enabled: true
    list:
      - tpahere
      - tpaccept
      - tpdeny
      - msg
      - tell
      - r
      - reply
      - kill
      - report

restrictions:
  banned_items:
    enabled: true
    items:
      - END_CRYSTAL

cooldowns:
  items:
    enabled: true
    seconds:
      GOLDEN_APPLE: 5
      END_CRYSTAL: 5
      ENDER_PEARL: 12
  blocks:
    enabled: true
    rules:
      COBWEB:
        seconds: 5
        decay_enabled: true
      OBSIDIAN:
        seconds: 10
        decay_enabled: false